#!/usr/bin/env python3

import html
import json
import pathlib
import re
import tomllib


ROOT = pathlib.Path(__file__).resolve().parents[2]
HACKS_DIR = ROOT / "src" / "hacks"
SITE_DIR = ROOT / "site"
HACKS_OUT_DIR = SITE_DIR / "_hacks"
TAGS_DIR = SITE_DIR / "tags"
SEARCH_JSON = SITE_DIR / "search.json"
INDEX_MD = SITE_DIR / "index.md"
GENERATED_COMMENT = "<!-- This file is generated by src/scripts/gen_site.py. Do not edit by hand. -->"

TOP_COMMENT_RE = re.compile(r"\A\s*/\*(.*?)\*/", re.DOTALL)
FUNC_RE_TEMPLATE = r"\bbh_output_t\s+{name}\s*\(\s*bh_input_t\s+\w+\s*\)\s*\{{"
IMPL_LIST_RE = re.compile(r"#define\s+BH_IMPLS\s*\(\s*X\s*\)(.*?)(?:\n\s*#|\Z)", re.DOTALL)
IMPL_ENTRY_RE = re.compile(r'X\s*\(\s*"([^"]+)"\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)')


def ensure_dir(path: pathlib.Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def extract_top_comment(text: str) -> str:
    match = TOP_COMMENT_RE.match(text)
    if match is None:
        raise ValueError("missing top metadata comment")
    return match.group(1).strip()


def extract_function(text: str, name: str) -> str:
    match = re.search(FUNC_RE_TEMPLATE.format(name=re.escape(name)), text)
    if match is None:
        raise ValueError(f"missing function {name}")

    start = match.start()
    brace_depth = 0
    index = text.find("{", match.start())
    if index < 0:
        raise ValueError(f"malformed function {name}")

    while index < len(text):
        char = text[index]
        if char == "{":
            brace_depth += 1
        elif char == "}":
            brace_depth -= 1
            if brace_depth == 0:
                return text[start:index + 1].strip()
        index += 1

    raise ValueError(f"unterminated function {name}")


def extract_impls(text: str) -> list[tuple[str, str]]:
    match = IMPL_LIST_RE.search(text)
    if match is None:
        return [("optimized", "bh_optimized")]

    impls = IMPL_ENTRY_RE.findall(match.group(1))
    if not impls:
        raise ValueError("BH_IMPLS is present but contains no implementations")
    return impls


def extract_typedef_decl(text: str, name: str) -> str:
    typedef_start = 0

    while True:
        typedef_start = text.find("typedef", typedef_start)
        if typedef_start < 0:
            raise ValueError(f"missing typedef for {name}")

        index = typedef_start
        brace_depth = 0
        while index < len(text):
            char = text[index]
            if char == "{":
                brace_depth += 1
            elif char == "}":
                brace_depth -= 1
            elif char == ";" and brace_depth == 0:
                decl = text[typedef_start:index + 1].strip()
                if re.search(rf"\b{name}\b\s*;$", decl):
                    return decl
                typedef_start = index + 1
                break
            index += 1
        else:
            raise ValueError(f"unterminated typedef for {name}")


def md_list(items: list[str]) -> str:
    if not items:
        return "- None\n"
    return "".join(f"- {item}\n" for item in items)


def json_list(items: list[str]) -> str:
    return json.dumps(items, ensure_ascii=False)


def clear_generated_tree(path: pathlib.Path) -> None:
    if not path.exists():
        return
    for child in sorted(path.iterdir()):
        if child.is_dir():
            clear_generated_tree(child)
            child.rmdir()
        else:
            child.unlink()


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "item"


def render_markdown(metadata: dict, relpath: str,
    input_typedef: str, output_typedef: str,
    optimized_impls: list[tuple[str, str]], reference_src: str) -> str:
    hack_url = f"/hacks/{metadata['hack_id']}/"
    front_matter = {
        "layout": "hack",
        "title": metadata["title"],
        "summary": metadata["summary"],
        "hack_id": metadata["hack_id"],
        "tags": metadata["tags"],
        "source_path": relpath,
        "slug": metadata["hack_id"],
        "permalink": hack_url,
    }
    lines = ["---"]
    for key, value in front_matter.items():
        if isinstance(value, list):
            lines.append(f"{key}: {json_list(value)}")
        else:
            lines.append(f'{key}: "{value}"')
    lines.extend(
        [
            "---",
            "",
            GENERATED_COMMENT,
            "",
            "## Summary",
            "",
            metadata["summary"],
            "",
            "## Contract",
            "",
            metadata["contract"],
            "",
            "## Notes",
            "",
            metadata["notes"].strip(),
            "",
            "## Reference Implementation",
            "",
            "```c",
            input_typedef,
            output_typedef,
            "",
            reference_src,
            "```",
            "",
            "## Source File",
            "",
            f"`{relpath}`",
            "",
            "## Sources",
            "",
            md_list(metadata["sources"]).rstrip(),
            "",
        ]
    )
    reference_index = lines.index("## Reference Implementation")
    if len(optimized_impls) == 1:
        lines[reference_index:reference_index] = [
            "## Optimized Implementation",
            "",
            "```c",
            input_typedef,
            output_typedef,
            "",
            optimized_impls[0][1],
            "```",
            "",
        ]
    else:
        optimized_block = [
            "## Optimized Implementations",
            "",
        ]
        for impl_name, impl_src in optimized_impls:
            optimized_block.extend(
                [
                    f"### {impl_name}",
                    "",
                    "```c",
                    input_typedef,
                    output_typedef,
                    "",
                    impl_src,
                    "```",
                    "",
                ]
            )
        lines[reference_index:reference_index] = optimized_block
    return "\n".join(lines)


def render_index(records: list[dict]) -> str:
    lines = [
        "---",
        'layout: default',
        'title: Bit Hacks',
        "---",
        "",
        GENERATED_COMMENT,
        "",
        "Standalone C implementations with differential verification, sanitizers, and fuzz smoke coverage.",
        "",
        '## [Search]({{ "/search.html" | relative_url }})',
        "",
        "## Verification",
        "",
        "- Strict Clang warnings in test and fuzz builds",
        "- Hand-written edge-case assertions in each `bh_tests` implementation",
        "- Deterministic random differential testing in generated test mains",
        "- libFuzzer smoke runs with address and undefined behavior sanitizers",
        "",
        "## Hacks",
        "",
        '<ul class="hack-list">',
    ]
    for record in records:
        summary = record["summary"]
        hack_path = record["url"]
        tag_links = ", ".join(
            '<a href="{{{{ "/tags/{}/" | relative_url }}}}">{}</a>'.format(
                slugify(tag), tag
            )
            for tag in record["tags"]
        )
        lines.append(
            '<li><a href="{{ "' + hack_path + '" | relative_url }}">' + record["title"] + '</a>'
            + (" — " + summary if summary else "")
            + (' <span class="tag-brackets">[' + tag_links + ']</span>' if tag_links else "")
            + '</li>'
        )
    lines.extend(["</ul>", "", "## Sources", ""])
    seen_sources = set()
    for record in records:
        for source in record["sources"]:
            if source in seen_sources:
                continue
            seen_sources.add(source)
            lines.append(f"- {source}")
    lines.append("")
    return "\n".join(lines)


def render_tag_index(tag: str) -> str:
    return "\n".join(
        [
            "---",
            "layout: tag",
            f'tag: "{tag}"',
            f'title: "Tag: {tag}"',
            f'permalink: "/tags/{slugify(tag)}/"',
            "---",
            "",
            GENERATED_COMMENT,
            "",
        ]
    )


def main() -> None:
    ensure_dir(HACKS_OUT_DIR)
    ensure_dir(TAGS_DIR)
    clear_generated_tree(HACKS_OUT_DIR)
    clear_generated_tree(TAGS_DIR)

    records = []
    all_tags = set()
    for hack_path in sorted(HACKS_DIR.glob("*.c")):
        text = hack_path.read_text(encoding="utf-8")
        metadata = tomllib.loads(extract_top_comment(text))
        optimized_impls = [
            (impl_name, extract_function(text, impl_fn))
            for impl_name, impl_fn in extract_impls(text)
        ]
        input_typedef = extract_typedef_decl(text, "bh_input_t")
        output_typedef = extract_typedef_decl(text, "bh_output_t")
        reference_src = extract_function(text, "bh_reference")
        relpath = str(hack_path.relative_to(ROOT))
        hack_url = f"/hacks/{metadata['hack_id']}/"

        markdown = render_markdown(
            metadata, relpath,
            input_typedef, output_typedef,
            optimized_impls, reference_src
        )
        md_out = HACKS_OUT_DIR / f"{metadata['hack_id']}.md"
        md_out.write_text(markdown, encoding="utf-8")

        records.append(
            {
                "title": metadata["title"],
                "hack_id": metadata["hack_id"],
                "tags": metadata["tags"],
                "summary": metadata["summary"],
                "contract": metadata["contract"],
                "path": relpath,
                "url": hack_url,
                "sources": metadata["sources"],
            }
        )
        for tag in metadata["tags"]:
            all_tags.add(tag)

    records.sort(key=lambda item: item["title"])
    for tag in sorted(all_tags):
        tag_dir = TAGS_DIR / slugify(tag)
        ensure_dir(tag_dir)
        (tag_dir / "index.md").write_text(render_tag_index(tag), encoding="utf-8")

    INDEX_MD.write_text(render_index(records), encoding="utf-8")
    SEARCH_JSON.write_text(json.dumps(records, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
